# Generated by Django 6.0.7 on 2026-07-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cobertura',
            field=models.CharField(blank=True, help_text='Ej: Chantilly, Fondant, Buttercream', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fruta',
            field=models.CharField(blank=True, help_text='Ej: Fresa, Durazno, Ninguna', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sabor',
            field=models.CharField(blank=True, help_text='Ejemplo: Chocolate, Vainilla, Fresa', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.CharField(blank=True, choices=[('PEQUEÑO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=20, null=True),
        ),
    ]
