# Generated by Django 6.0.7 on 2026-07-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_cobertura_producto_fruta_producto_sabor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nivel_dulzura',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20, null=True),
        ),
    ]
