# Generated by Django 6.0.7 on 2026-07-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_nivel_dulzura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del postre', null=True),
        ),
    ]
